var ORDER_STATUS_PENDING="pending";
var ORDER_STATUS_CONFIRMED="confirmed";
var ORDER_STATUS_PAYED="payed";
var ORDER_STATUS_COMPLETED="completed";
var ORDER_STATUS_CANCELED="canceled";

var ORDER_ITEM_STATUS_PENDING="pending";
var ORDER_ITEM_STATUS_SHIPPED="shipped";
var ORDER_ITEM_STATUS_RECEIVED="received";
var ORDER_ITEM_STATUS_CANCELED="canceled";

var PAYMENT_STATUS_AUTH = "auth";
var PAYMENT_STATUS_SETTLING  = "settling";
var PAYMENT_STATUS_SETTLEMENT  = "settlement";
var PAYMENT_STATUS_VOID = "void";
var PAYMENT_STATUS_REFUND = "refund";

var PAYMENT_TYPE_PAYPAL = "paypal";
var PAYMENT_TYPE_CREDITCARD = "creditcard";
var PAYMENT_TYPE_ALIPAY = "alipay";
var PAYMENT_TYPE_WECHAT ="wechat";

var PERMISSION_GETORDERS ="getOrders";
var PERMISSION_UPDATEORDERS ="updateOrders";
var PERMISSION_GETBIZORDERS ="getBizOrders";
var PERMISSION_UPDATEBIZORDERS ="updateBizOrders";
var PERMISSION_GETPAYMENTS ="getPayments";
var PERMISSION_CREATEPAYMENTS ="createPayments";
var PERMISSION_GETCHANGEHISTORIES="getCheckoutChangeHistories"

var HISTORY_ITEM_TYPE_ORDER="order";
var HISTORY_ITEM_TYPE_ORDERITEM="order item";



module.exports = {
    ORDER_STATUS_PENDING:ORDER_STATUS_PENDING,
    ORDER_STATUS_PAYED:ORDER_STATUS_PAYED,
    ORDER_STATUS_COMPLETED:ORDER_STATUS_COMPLETED,
    ORDER_STATUS_CANCELED: ORDER_STATUS_CANCELED,
    ORDER_STATUS_CONFIRMED:ORDER_STATUS_CONFIRMED,

    ORDER_ITEM_STATUS_PENDING:ORDER_ITEM_STATUS_PENDING,
    ORDER_ITEM_STATUS_SHIPPED:ORDER_ITEM_STATUS_SHIPPED,
    ORDER_ITEM_STATUS_RECEIVED:ORDER_ITEM_STATUS_RECEIVED,
    ORDER_ITEM_STATUS_CANCELED:ORDER_ITEM_STATUS_CANCELED,

    PAYMENT_STATUS_AUTH:PAYMENT_STATUS_AUTH,
    PAYMENT_STATUS_SETTLING: PAYMENT_STATUS_SETTLING,
    PAYMENT_STATUS_SETTLEMENT:PAYMENT_STATUS_SETTLEMENT,
    PAYMENT_STATUS_VOID: PAYMENT_STATUS_VOID,
    PAYMENT_STATUS_REFUND:PAYMENT_STATUS_REFUND,

    PAYMENT_TYPE_PAYPAL: PAYMENT_TYPE_PAYPAL,
    PAYMENT_TYPE_CREDITCARD: PAYMENT_TYPE_CREDITCARD,
    PAYMENT_TYPE_ALIPAY:PAYMENT_TYPE_ALIPAY,
    PAYMENT_TYPE_WECHAT:PAYMENT_TYPE_WECHAT,

    PERMISSION_GETORDERS:PERMISSION_GETORDERS,
    PERMISSION_GETPAYMENTS: PERMISSION_GETPAYMENTS,
    PERMISSION_CREATEPAYMENTS:PERMISSION_CREATEPAYMENTS,
    PERMISSION_GETBIZORDERS:PERMISSION_GETBIZORDERS,
    PERMISSION_UPDATEORDERS:PERMISSION_UPDATEORDERS,
    PERMISSION_UPDATEBIZORDERS:PERMISSION_UPDATEBIZORDERS,
    PERMISSION_GETCHANGEHISTORIES:PERMISSION_GETCHANGEHISTORIES,

    HISTORY_ITEM_TYPE_ORDER:HISTORY_ITEM_TYPE_ORDER,
    HISTORY_ITEM_TYPE_ORDERITEM:HISTORY_ITEM_TYPE_ORDERITEM
}